"""
Command service for processing MUSH-style commands.

This service detects commands (messages starting with /), parses them,
and routes them through the plugin engine for execution.
"""
import re
import logging
from typing import Dict, Any, List, Tuple, Optional
from datetime import datetime, UTC

from ..core.plugin_engine import PluginEngine

logger = logging.getLogger(__name__)


class CommandService:
    """Service for detecting and processing MUSH-style commands."""
    
    # Regex pattern to match commands: /command args...
    COMMAND_PATTERN = re.compile(r'^/(\w+)\s*(.*)$')
    
    def __init__(self):
        """Initialize the command service."""
        self.plugin_engine = PluginEngine()
    
    @staticmethod
    def is_command(text: str) -> bool:
        """
        Check if a message is a command.
        
        Args:
            text: The message text to check
            
        Returns:
            True if the message starts with /, False otherwise
        """
        if not text or not isinstance(text, str):
            return False
        
        return text.strip().startswith('/')
    
    @staticmethod
    def parse_command(text: str) -> Optional[Tuple[str, List[str]]]:
        """
        Parse a command message into command name and arguments.
        
        Args:
            text: The command text (e.g., "/roll 1d20" or "/help")
            
        Returns:
            Tuple of (command_name, args) where args is a list of arguments,
            or None if the text is not a valid command
            
        Examples:
            "/roll 1d20" -> ("roll", ["1d20"])
            "/help" -> ("help", [])
            "/kick @user reason" -> ("kick", ["@user", "reason"])
        """
        if not text:
            return None
        
        match = CommandService.COMMAND_PATTERN.match(text.strip())
        if not match:
            return None
        
        command_name = match.group(1).lower()
        args_string = match.group(2).strip()
        
        # Split arguments by whitespace, preserving quoted strings
        args = args_string.split() if args_string else []
        
        return (command_name, args)
    
    def execute_command(
        self,
        text: str,
        user_id: str,
        scene_id: str,
        character_name: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Execute a command through the plugin engine.
        
        Args:
            text: The command text (e.g., "/roll 1d20")
            user_id: ID of the user executing the command
            scene_id: ID of the scene where the command is executed
            character_name: Optional name of the character executing the command
            
        Returns:
            Dictionary with execution results:
                - success: bool - Whether the command executed successfully
                - command: str - The command name
                - system_messages: List[str] - System messages generated by plugins
                - error: Optional[str] - Error message if execution failed
        """
        try:
            # Parse the command
            parsed = self.parse_command(text)
            if not parsed:
                return {
                    'success': False,
                    'error': 'Invalid command format',
                    'system_messages': []
                }
            
            command_name, args = parsed
            
            logger.info(f"Executing command: {command_name} with args: {args} for user: {user_id}")
            
            # Prepare command payload for plugin engine
            command_payload = {
                'command': command_name,
                'args': args,
                'user_id': user_id,
                'scene_id': scene_id,
                'character_name': character_name,
                'timestamp': datetime.now(UTC).isoformat()
            }
            
            # Load plugin context for this user and scene
            try:
                self.plugin_engine.load_context(user_id, scene_id)
            except Exception as e:
                logger.warning(f"Failed to load plugin context: {str(e)}")
                # Continue anyway - commands might work without plugins
            
            # Trigger the ON_COMMAND event through the plugin engine
            result = self.plugin_engine.trigger_event(
                'ON_COMMAND',
                command_payload,
                context={'user_id': user_id, 'scene_id': scene_id}
            )
            
            # Extract system messages from plugin results
            system_messages = []
            
            if result:
                # Check if result contains system messages
                if isinstance(result, dict):
                    if 'system_message' in result:
                        system_messages.append(result['system_message'])
                    elif 'message' in result:
                        system_messages.append(result['message'])
                    elif 'messages' in result and isinstance(result['messages'], list):
                        system_messages.extend(result['messages'])
                elif isinstance(result, str):
                    system_messages.append(result)
            
            # If no plugins handled the command, return a default message
            if not system_messages:
                system_messages.append(f"Command '{command_name}' executed (no plugin response)")
            
            logger.info(f"Command executed successfully: {len(system_messages)} system messages generated")
            
            return {
                'success': True,
                'command': command_name,
                'args': args,
                'system_messages': system_messages
            }
            
        except Exception as e:
            logger.error(f"Error executing command: {str(e)}", exc_info=True)
            return {
                'success': False,
                'command': text,
                'error': str(e),
                'system_messages': [f"Error executing command: {str(e)}"]
            }
        finally:
            # Clear the plugin context
            self.plugin_engine.clear_context()
    
    def get_available_commands(self, user_id: str, scene_id: Optional[str] = None) -> List[str]:
        """
        Get a list of available commands for a user.
        
        This is determined by which plugins the user has installed.
        
        Args:
            user_id: ID of the user
            scene_id: Optional scene ID for scene-specific plugins
            
        Returns:
            List of available command names
        """
        try:
            # Load the user's plugin context
            self.plugin_engine.load_context(user_id, scene_id)
            
            # Get loaded plugins
            loaded_plugins = self.plugin_engine.get_loaded_plugins()
            
            logger.info(f"User {user_id} has {len(loaded_plugins)} plugins loaded")
            
            return loaded_plugins
            
        except Exception as e:
            logger.error(f"Error getting available commands: {str(e)}")
            return []
        finally:
            self.plugin_engine.clear_context()
